version: "3.9"
services:
  app:
    build: .
    image: go-whatsapp-app:latest
    container_name: go-whatsapp-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - /root/autoreply/data:/app
    environment:
      - TZ=Asia/Jakarta
